/**
 * Bundled demo family trees for onboarding. Chosen by UI language: Czech users
 * get the Přemyslid dynasty, everyone else the House of Tudor — the app targets
 * an international audience, so the default demo must not be region-specific.
 * The data ships inside the app (no download), works offline and in the
 * single-file export.
 *
 * Historical data from public sources (Wikipedia/Britannica). Early Přemyslid
 * dates are uncertain and intentionally use flex-date qualifiers (~ / <), which
 * doubles as a showcase of that feature. Multiple marriages (Ottokar I & II,
 * Wenceslaus II; Henry VIII's six wives) showcase partner chains.
 *
 * Places are only given where history is reasonably sure of them (mostly deaths
 * of rulers, which were recorded); a guess would be worse than a blank. Their
 * coordinates ship WITH the demo (PREMYSLID_PLACES / TUDOR_PLACES, generated by
 * scripts/geocode-demo.ts), so the map view works the moment the demo loads —
 * no lookup, nothing sent anywhere. Only the map tiles need the internet.
 */

import {
    StromData, Person, Partnership, PersonId, PartnershipId, Gender, PlaceGeo,
    toPersonId, toPartnershipId, STROM_DATA_VERSION,
} from './types.js';

interface PersonOpts {
    birthDate?: string;
    deathDate?: string;
    birthPlace?: string;
    deathPlace?: string;
    notes?: string;
}

/** Small deterministic builder — no Date.now / Math.random, stable IDs. */
class DemoBuilder {
    private persons: Record<PersonId, Person> = {};
    private partnerships: Record<PartnershipId, Partnership> = {};

    constructor(private prefix: string) {}

    person(id: string, firstName: string, lastName: string, gender: Gender, opts: PersonOpts = {}): PersonId {
        const pid = toPersonId(`${this.prefix}_${id}`);
        const p: Person = {
            id: pid, firstName, lastName, gender,
            isPlaceholder: false, partnerships: [], parentIds: [], childIds: [],
        };
        if (opts.birthDate) p.birthDate = opts.birthDate;
        if (opts.deathDate) p.deathDate = opts.deathDate;
        if (opts.birthPlace) p.birthPlace = opts.birthPlace;
        if (opts.deathPlace) p.deathPlace = opts.deathPlace;
        if (opts.notes) p.notes = opts.notes;
        this.persons[pid] = p;
        return pid;
    }

    /** Marry two people. The male partner is person1 (rendered left), as elsewhere. */
    marry(a: PersonId, b: PersonId): PartnershipId {
        let p1 = a, p2 = b;
        if (this.persons[a].gender === 'female' && this.persons[b].gender === 'male') {
            p1 = b; p2 = a;
        }
        const uid = toPartnershipId(`u_${p1}_${p2}`);
        this.partnerships[uid] = { id: uid, person1Id: p1, person2Id: p2, childIds: [], status: 'married' };
        this.persons[p1].partnerships.push(uid);
        this.persons[p2].partnerships.push(uid);
        return uid;
    }

    kids(union: PartnershipId, ...children: PersonId[]): void {
        const u = this.partnerships[union];
        for (const c of children) {
            u.childIds.push(c);
            this.persons[c].parentIds = [u.person1Id, u.person2Id];
            if (!this.persons[u.person1Id].childIds.includes(c)) this.persons[u.person1Id].childIds.push(c);
            if (!this.persons[u.person2Id].childIds.includes(c)) this.persons[u.person2Id].childIds.push(c);
        }
    }

    build(places: Record<string, PlaceGeo>): StromData {
        return {
            version: STROM_DATA_VERSION,
            persons: this.persons,
            partnerships: this.partnerships,
            places,
        };
    }
}

/**
 * Coordinates for the places above, generated by scripts/geocode-demo.ts
 * (npm run gen:demo-places). Shipped with the demo so the map works the moment
 * it loads — nothing is looked up and nothing is sent anywhere.
 */
const PREMYSLID_PLACES: Record<string, PlaceGeo> = {
    'levy hradec': { lat: 50.1693, lon: 14.3753, label: "Levý Hradec, Žalov, Roztoky, okres Praha-západ, Středočeský kraj, 252 63, Česko" },
    'tetin': { lat: 49.9493, lon: 14.1022, label: "Tetín, okres Beroun, Středočeský kraj, Česko" },
    'praha': { lat: 50.0875, lon: 14.4213, label: "Praha, Česko" },
    'stara boleslav': { lat: 50.1994, lon: 14.679, label: "Stará Boleslav, Brandýs nad Labem-Stará Boleslav, okres Praha-východ, Středočeský kraj, Česko" },
    'hnezdno': { lat: 52.5247, lon: 17.5982, label: "Gniezno, powiat gnieźnieński, województwo wielkopolskie, Polska" },
    'melnik': { lat: 50.3521, lon: 14.4748, label: "Mělník, okres Mělník, Středočeský kraj, 276 01, Česko" },
    'lysa nad labem': { lat: 50.2017, lon: 14.8328, label: "Lysá nad Labem, okres Nymburk, Středočeský kraj, 289 22, Česko" },
    'chrudim': { lat: 49.9511, lon: 15.7948, label: "Chrudim, okres Chrudim, Pardubický kraj, Česko" },
    'svinibrod': { lat: 50.0451, lon: 10.2341, label: "Schweinfurt, Bayern, Deutschland" },
    'vysehrad': { lat: 50.0642, lon: 14.4194, label: "Vyšehrad, Štulcova, Vyšehrad, obvod Praha 2, Praha, 128 00, Česko" },
    'meerane': { lat: 50.8428, lon: 12.4582, label: "Meerane, Meerane-Schönberg, Zwickau, Sachsen, 08393, Deutschland" },
    'misen': { lat: 51.1631, lon: 13.4705, label: "Meißen, Sachsen, Deutschland" },
    'predklasteri': { lat: 49.3525, lon: 16.4024, label: "Předklášteří, okres Brno-venkov, Jihomoravský kraj, 666 02, Česko" },
    'pocaply': { lat: 49.9419, lon: 14.0237, label: "Počaply, Karlova Huť, Králův Dvůr, okres Beroun, Středočeský kraj, 267 01, Česko" },
    'suche kruty': { lat: 48.4718, lon: 16.8499, label: "Dürnkrut, Bezirk Gänserndorf, Niederösterreich, 2263, Österreich" },
    'viden': { lat: 48.2084, lon: 16.3725, label: "Wien, Österreich" },
    'rheinfelden': { lat: 47.5544, lon: 7.7923, label: "Rheinfelden, Bezirk Rheinfelden, Aargau, 4310, Schweiz/Suisse/Svizzera/Svizra" },
    'poznan': { lat: 52.4007, lon: 16.9197, label: "Poznań, powiat poznański, województwo wielkopolskie, Polska" },
    'brno': { lat: 49.1922, lon: 16.6113, label: "Brno, okres Brno-město, Jihomoravský kraj, Česko" },
    'olomouc': { lat: 49.5941, lon: 17.2511, label: "Olomouc, okres Olomouc, Olomoucký kraj, Česko" },
    'vratislav': { lat: 51.1263, lon: 16.9782, label: "Wrocław, województwo dolnośląskie, Polska" },
    'tesin': { lat: 49.7558, lon: 18.6562, label: "Cieszyn, powiat cieszyński, województwo śląskie, 43-400, Polska" },
};

const TUDOR_PLACES: Record<string, PlaceGeo> = {
    'much hadham': { lat: 51.8466, lon: 0.0708, label: "Much Hadham, East Hertfordshire, Hertfordshire, England, United Kingdom" },
    'carmarthen': { lat: 51.8591, lon: -4.3116, label: "Carmarthen, Sir Gaerfyrddin / Carmarthenshire, Cymru / Wales, SA31 1RT, United Kingdom" },
    'bletsoe': { lat: 52.2223, lon: -0.4983, label: "Bletsoe, Bedford, England, United Kingdom" },
    'westminster': { lat: 51.5004, lon: -0.1265, label: "Westminster, Millbank, City of Westminster, Greater London, England, SW1P 3JX, United Kingdom" },
    'pembroke castle': { lat: 51.6772, lon: -4.9208, label: "Pembroke Castle, Castle Walk, Monkton, Pembroke, Pembrokeshire, Cymru / Wales, SA71 4NY, United Kingdom" },
    'richmond london': { lat: 51.4406, lon: -0.3076, label: "London Borough of Richmond upon Thames, Greater London, England, United Kingdom" },
    'tower of london': { lat: 51.5082, lon: -0.0762, label: "Tower of London, Tower Hill, East Smithfield, Tower Hill, Whitechapel, London Borough of Tower Hamlets, Greater London, England, EC3N 4AB, United Kingdom" },
    'winchester': { lat: 51.0613, lon: -1.3132, label: "Winchester, Hampshire, England, SO23 9LF, United Kingdom" },
    'ludlow castle': { lat: 52.3672, lon: -2.723, label: "Ludlow Castle, Events Square, Ludlow, Shropshire, England, SY8 1AY, United Kingdom" },
    'methven': { lat: 56.4157, lon: -3.5795, label: "Methven, Perth and Kinross, Alba / Scotland, PH1 3PQ, United Kingdom" },
    'greenwich': { lat: 51.4821, lon: -0.0045, label: "Greenwich, Greater London, England, SE10 9HF, United Kingdom" },
    'whitehall london': { lat: 51.5037, lon: -0.1262, label: "Whitehall, Westminster, Covent Garden, City of Westminster, Greater London, England, SW1A 2AG, United Kingdom" },
    'westhorpe': { lat: 52.282, lon: 0.9929, label: "Westhorpe, Mid Suffolk, Suffolk, England, United Kingdom" },
    'alcala de henares': { lat: 40.482, lon: -3.364, label: "Alcalá de Henares, Comunidad de Madrid, España" },
    'kimbolton': { lat: 52.3035, lon: -0.3814, label: "Kimbolton, Huntingdonshire, Cambridgeshire, Cambridgeshire and Peterborough, England, United Kingdom" },
    'blickling': { lat: 52.814, lon: 1.2279, label: "Blickling, Broadland, Norfolk, England, United Kingdom" },
    'wolfhall': { lat: 51.3556, lon: -1.6543, label: "Wolfhall, Wolfhall Road, Eastcourt, Burbage, Wiltshire, England, SN8 3DP, United Kingdom" },
    'hampton court': { lat: 51.4037, lon: -0.3377, label: "Hampton Court Palace, Clock Court, Hampton Wick, London Borough of Richmond upon Thames, Greater London, England, KT8 9AU, United Kingdom" },
    'dusseldorf': { lat: 51.2254, lon: 6.7763, label: "Düsseldorf, Nordrhein-Westfalen, Deutschland" },
    'chelsea london': { lat: 51.4889, lon: -0.1654, label: "Chelsea, Royal Borough of Kensington and Chelsea, Greater London, England, SW3 4UT, United Kingdom" },
    'sudeley castle': { lat: 51.9474, lon: -1.9564, label: "Sudeley Castle, Rushley Lane, Sudeley, Cheltenham, Gloucestershire, England, GL54 5JD, United Kingdom" },
    "st james's palace": { lat: 51.5045, lon: -0.1378, label: "Saint James's Palace, St. James's Street, St. James's, Westminster, Victoria, City of Westminster, Greater London, England, SW1A 1EG, United Kingdom" },
    'valladolid': { lat: 41.62, lon: -4.726, label: "Valladolid, Castilla y León, España" },
    'el escorial': { lat: 40.5836, lon: -4.1281, label: "El Escorial, Comunidad de Madrid, España" },
    'branxton': { lat: 55.6318, lon: -2.1692, label: "Branxton, Northumberland, North East, England, United Kingdom" },
    'linlithgow': { lat: 55.9787, lon: -3.6006, label: "Linlithgow Palace, Kirkgate, Linlithgow, West Lothian, Alba / Scotland, EH49 7AH, United Kingdom" },
    'falkland': { lat: 56.2531, lon: -3.208, label: "Falkland, Fife, Alba / Scotland, KY15 7BU, United Kingdom" },
    'bar-le-duc': { lat: 48.7713, lon: 5.1624, label: "Bar-le-Duc, Meuse, Grand Est, France métropolitaine, 55000, France" },
    'edinburgh': { lat: 55.9533, lon: -3.1884, label: "City of Edinburgh, Alba / Scotland, United Kingdom" },
    'fotheringhay': { lat: 52.526, lon: -0.4376, label: "Fotheringhay, North Northamptonshire, England, United Kingdom" },
    'guildford': { lat: 51.2356, lon: -0.5732, label: "Guildford, Surrey, England, GU1 3DP, United Kingdom" },
    'hatfield': { lat: 51.7635, lon: -0.2259, label: "Hatfield, Welwyn Hatfield, Hertfordshire, England, United Kingdom" },
    'bradgate park': { lat: 52.69, lon: -1.2159, label: "Bradgate Park, Newtown Linford, Charnwood, Leicestershire, England, LE6 0HE, United Kingdom" },
};

// ==================== PŘEMYSLOVCI ====================

function buildPremyslids(): { data: StromData; focus: PersonId } {
    const b = new DemoBuilder('pr');

    const borivoj = b.person('borivoj', 'Bořivoj I.', 'Přemyslovec', 'male', { birthDate: '~852', deathDate: '~889', deathPlace: 'Levý Hradec', notes: 'První historicky doložený přemyslovský kníže, pokřtěný svatým Metodějem.' });
    const ludmila = b.person('ludmila', 'Ludmila', 'ze Pšova', 'female', { birthDate: '~860', deathDate: '921', deathPlace: 'Tetín', notes: 'Svatá Ludmila, babička sv. Václava; zavražděna z popudu Drahomíry.' });
    const uBorivoj = b.marry(borivoj, ludmila);
    const spytihnev1 = b.person('spytihnev1', 'Spytihněv I.', 'Přemyslovec', 'male', { birthDate: '~875', deathDate: '915' });
    const vratislav1 = b.person('vratislav1', 'Vratislav I.', 'Přemyslovec', 'male', { birthDate: '~888', deathDate: '921' });
    b.kids(uBorivoj, spytihnev1, vratislav1);

    const drahomira = b.person('drahomira', 'Drahomíra', 'ze Stodor', 'female', { birthDate: '~890', deathDate: '>935' });
    const uVratislav1 = b.marry(vratislav1, drahomira);
    const vaclav = b.person('vaclav', 'Václav I.', 'Přemyslovec', 'male', { birthDate: '~907', deathDate: '935', birthPlace: 'Praha', deathPlace: 'Stará Boleslav', notes: 'Svatý Václav, patron české země; zavražděn bratrem Boleslavem ve Staré Boleslavi.' });
    const boleslav1 = b.person('boleslav1', 'Boleslav I.', 'Přemyslovec', 'male', { birthDate: '~915', deathDate: '972', deathPlace: 'Praha', notes: 'Zvaný Ukrutný; za jeho vlády vzniklo pražské biskupství.' });
    b.kids(uVratislav1, vaclav, boleslav1);

    const biagota = b.person('biagota', 'Biagota', '', 'female', { birthDate: '~920' });
    const uBoleslav1 = b.marry(boleslav1, biagota);
    const boleslav2 = b.person('boleslav2', 'Boleslav II.', 'Přemyslovec', 'male', { birthDate: '~932', deathDate: '999', deathPlace: 'Praha', notes: 'Zvaný Pobožný; podporoval sv. Vojtěcha.' });
    const doubravka = b.person('doubravka', 'Doubravka', 'Přemyslovna', 'female', { deathPlace: 'Hnězdno', birthDate: '~940', deathDate: '977' });
    b.kids(uBoleslav1, boleslav2, doubravka);

    const emma = b.person('emma', 'Emma', 'z Mělníka', 'female', { deathPlace: 'Mělník', birthDate: '~950', deathDate: '1006' });
    const uBoleslav2 = b.marry(boleslav2, emma);
    const boleslav3 = b.person('boleslav3', 'Boleslav III.', 'Přemyslovec', 'male', { birthDate: '~965', deathDate: '1037' });
    const jaromir = b.person('jaromir', 'Jaromír', 'Přemyslovec', 'male', { deathPlace: 'Lysá nad Labem', birthDate: '~975', deathDate: '1035' });
    const oldrich = b.person('oldrich', 'Oldřich', 'Přemyslovec', 'male', { birthDate: '~975', deathDate: '1034' });
    b.kids(uBoleslav2, boleslav3, jaromir, oldrich);

    const bozena = b.person('bozena', 'Božena', '', 'female', { birthDate: '~995', deathDate: '1052' });
    const uOldrich = b.marry(oldrich, bozena);
    const bretislav1 = b.person('bretislav1', 'Břetislav I.', 'Přemyslovec', 'male', { birthDate: '~1002', deathDate: '1055', deathPlace: 'Chrudim', notes: 'Zvaný Achilles; unesl si Jitku ze Svinibrodu z kláštera.' });
    b.kids(uOldrich, bretislav1);

    const jitka = b.person('jitka', 'Jitka', 'ze Svinibrodu', 'female', { birthPlace: 'Svinibrod', birthDate: '~1003', deathDate: '1058' });
    const uBretislav1 = b.marry(bretislav1, jitka);
    const spytihnev2 = b.person('spytihnev2', 'Spytihněv II.', 'Přemyslovec', 'male', { deathPlace: 'Praha', birthDate: '1031', deathDate: '1061' });
    const vratislav2 = b.person('vratislav2', 'Vratislav II.', 'Přemyslovec', 'male', { birthDate: '~1032', deathDate: '1092', deathPlace: 'Praha', notes: 'První český král (1085), titul osobní, nedědičný.' });
    const konrad1 = b.person('konrad1', 'Konrád I.', 'Brněnský', 'male', { deathPlace: 'Praha', birthDate: '~1035', deathDate: '1092' });
    b.kids(uBretislav1, spytihnev2, vratislav2, konrad1);

    const svatava = b.person('svatava', 'Svatava', 'Polská', 'female', { deathPlace: 'Praha', birthDate: '~1046', deathDate: '1126' });
    const uVratislav2 = b.marry(vratislav2, svatava);
    const borivoj2 = b.person('borivoj2', 'Bořivoj II.', 'Přemyslovec', 'male', { birthDate: '~1064', deathDate: '1124' });
    const vladislav1 = b.person('vladislav1', 'Vladislav I.', 'Přemyslovec', 'male', { deathPlace: 'Vyšehrad', birthDate: '~1065', deathDate: '1125' });
    const sobeslav1 = b.person('sobeslav1', 'Soběslav I.', 'Přemyslovec', 'male', { birthDate: '~1075', deathDate: '1140' });
    b.kids(uVratislav2, borivoj2, vladislav1, sobeslav1);

    const richenza = b.person('richenza', 'Richenza', 'z Bergu', 'female', { birthDate: '~1095', deathDate: '1125' });
    const uVladislav1 = b.marry(vladislav1, richenza);
    const vladislav2 = b.person('vladislav2', 'Vladislav II.', 'Přemyslovec', 'male', { birthDate: '~1110', deathDate: '1174', deathPlace: 'Meerane', notes: 'Druhý český král (1158), korunován Fridrichem Barbarossou.' });
    b.kids(uVladislav1, vladislav2);

    // Vladislav II married twice: Gertruda (mother of Bedřich) and Judita of
    // Thuringia (mother of Přemysl Otakar I. — Gertruda died before his birth).
    const gertruda = b.person('gertruda', 'Gertruda', 'Babenberská', 'female', { deathPlace: 'Praha', birthDate: '~1118', deathDate: '1150' });
    const uVladislav2 = b.marry(vladislav2, gertruda);
    const bedrich = b.person('bedrich', 'Bedřich', 'Přemyslovec', 'male', { birthDate: '~1142', deathDate: '1189' });
    b.kids(uVladislav2, bedrich);
    const juditaD = b.person('judita_d', 'Judita', 'Durynská', 'female', { birthDate: '~1135', deathDate: '~1174' });
    const uVladislav2j = b.marry(vladislav2, juditaD);
    const otakar1 = b.person('otakar1', 'Přemysl Otakar I.', 'Přemyslovec', 'male', { birthDate: '~1155', deathDate: '1230', deathPlace: 'Praha', notes: 'Získal Zlatou bulou sicilskou (1212) dědičný královský titul.' });
    b.kids(uVladislav2j, otakar1);

    // Multiple marriages: Adléta (dissolved) then Constance of Hungary.
    const adleta = b.person('adleta', 'Adléta', 'Míšeňská', 'female', { birthPlace: 'Míšeň', deathPlace: 'Míšeň', birthDate: '~1160', deathDate: '1211' });
    b.marry(otakar1, adleta);
    const constance = b.person('constance', 'Konstancie', 'Uherská', 'female', { deathPlace: 'Předklášteří', birthDate: '~1180', deathDate: '1240' });
    const uOtakar1c = b.marry(otakar1, constance);
    const vaclav1k = b.person('vaclav1k', 'Václav I.', 'Přemyslovec', 'male', { birthDate: '~1205', deathDate: '1253', deathPlace: 'Počáply', notes: 'Zvaný Jednooký; ubránil zemi před Mongoly.' });
    const anezka = b.person('anezka', 'Anežka', 'Česká', 'female', { birthDate: '~1211', deathDate: '1282', birthPlace: 'Praha', deathPlace: 'Praha', notes: 'Svatá Anežka Česká, zakladatelka špitálu a řádu křižovníků.' });
    const premyslMar = b.person('premysl_mar', 'Přemysl', 'Moravský', 'male', { birthDate: '~1209', deathDate: '1239' });
    b.kids(uOtakar1c, vaclav1k, anezka, premyslMar);

    const kunhutaH = b.person('kunhuta_h', 'Kunhuta', 'Štaufská', 'female', { deathPlace: 'Praha', birthDate: '~1200', deathDate: '1248' });
    const uVaclav1k = b.marry(vaclav1k, kunhutaH);
    const otakar2 = b.person('otakar2', 'Přemysl Otakar II.', 'Přemyslovec', 'male', { birthDate: '~1233', deathDate: '1278', deathPlace: 'Suché Kruty', notes: 'Král železný a zlatý; padl v bitvě na Moravském poli.' });
    b.kids(uVaclav1k, otakar2);

    // Multiple marriages: Margaret of Austria (dissolved) then Kunigunda.
    const margaretR = b.person('margaret_r', 'Markéta', 'Babenberská', 'female', { birthPlace: 'Vídeň', birthDate: '~1204', deathDate: '1266' });
    b.marry(otakar2, margaretR);
    const kunhutaHal = b.person('kunhuta_hal', 'Kunhuta', 'Haličská', 'female', { deathPlace: 'Praha', birthDate: '~1245', deathDate: '1285' });
    const uOtakar2k = b.marry(otakar2, kunhutaHal);
    const vaclav2 = b.person('vaclav2', 'Václav II.', 'Přemyslovec', 'male', { birthDate: '1271', deathDate: '1305', birthPlace: 'Praha', deathPlace: 'Praha', notes: 'Král český a polský; zavedl pražský groš.' });
    b.kids(uOtakar2k, vaclav2);

    // Multiple marriages: Judith of Habsburg then Elizabeth Richeza.
    const judita = b.person('judita', 'Guta', 'Habsburská', 'female', { birthPlace: 'Rheinfelden', deathPlace: 'Praha', birthDate: '1271', deathDate: '1297' });
    const uVaclav2j = b.marry(vaclav2, judita);
    const rejcka = b.person('rejcka', 'Eliška', 'Rejčka', 'female', { birthPlace: 'Poznaň', deathPlace: 'Brno', birthDate: '1288', deathDate: '1335' });
    b.marry(vaclav2, rejcka);
    const vaclav3 = b.person('vaclav3', 'Václav III.', 'Přemyslovec', 'male', { birthDate: '1289', deathDate: '1306', birthPlace: 'Praha', deathPlace: 'Olomouc', notes: 'Poslední Přemyslovec po meči; zavražděn v Olomouci roku 1306.' });
    const eliskaP = b.person('eliska_p', 'Eliška', 'Přemyslovna', 'female', { birthDate: '1292', deathDate: '1330', birthPlace: 'Praha', deathPlace: 'Praha', notes: 'Matka císaře Karla IV.' });
    const annaP = b.person('anna_p', 'Anna', 'Přemyslovna', 'female', { birthPlace: 'Praha', deathPlace: 'Vratislav', birthDate: '1290', deathDate: '1313' });
    b.kids(uVaclav2j, vaclav3, eliskaP, annaP);

    const viola = b.person('viola', 'Viola', 'Těšínská', 'female', { birthPlace: 'Těšín', deathPlace: 'Praha', birthDate: '~1290', deathDate: '1317' });
    b.marry(vaclav3, viola);

    return { data: b.build(PREMYSLID_PLACES), focus: vaclav };
}

// ==================== HOUSE OF TUDOR ====================

function buildTudors(): { data: StromData; focus: PersonId } {
    const b = new DemoBuilder('td');

    const edmund = b.person('edmund', 'Edmund', 'Tudor', 'male', { birthDate: '~1430', deathDate: '1456', birthPlace: 'Much Hadham', deathPlace: 'Carmarthen', notes: 'Earl of Richmond; half-brother of Henry VI.' });
    const margaretBf = b.person('margaret_bf', 'Margaret', 'Beaufort', 'female', { birthDate: '1443', deathDate: '1509', birthPlace: 'Bletsoe', deathPlace: 'Westminster', notes: 'Mother of Henry VII; a key figure behind his claim to the throne.' });
    const uEdmund = b.marry(edmund, margaretBf);

    const henry7 = b.person('henry7', 'Henry VII', 'Tudor', 'male', { birthDate: '1457', deathDate: '1509', birthPlace: 'Pembroke Castle', deathPlace: 'Richmond, London', notes: 'First Tudor king; won the crown at Bosworth Field, ending the Wars of the Roses.' });
    b.kids(uEdmund, henry7);
    const elizabethY = b.person('elizabeth_y', 'Elizabeth', 'of York', 'female', { birthDate: '1466', deathDate: '1503', birthPlace: 'Westminster', deathPlace: 'Tower of London', notes: 'Her marriage united the houses of Lancaster and York.' });
    const uHenry7 = b.marry(henry7, elizabethY);
    const arthur = b.person('arthur', 'Arthur', 'Tudor', 'male', { birthDate: '1486', deathDate: '1502', birthPlace: 'Winchester', deathPlace: 'Ludlow Castle', notes: 'Prince of Wales; died months after marrying Catherine of Aragon.' });
    const margaretT = b.person('margaret_t', 'Margaret', 'Tudor', 'female', { birthPlace: 'Westminster', deathPlace: 'Methven', birthDate: '1489', deathDate: '1541' });
    const henry8 = b.person('henry8', 'Henry VIII', 'Tudor', 'male', { birthDate: '1491', deathDate: '1547', birthPlace: 'Greenwich', deathPlace: 'Whitehall, London', notes: 'Broke with Rome to annul his first marriage; had six wives.' });
    const maryT = b.person('mary_t', 'Mary', 'Tudor', 'female', { birthPlace: 'Richmond, London', deathPlace: 'Westhorpe', birthDate: '1496', deathDate: '1533' });
    b.kids(uHenry7, arthur, margaretT, henry8, maryT);

    // Catherine of Aragon married Arthur, then Henry VIII (a partner chain).
    const catherineA = b.person('catherine_a', 'Catherine', 'of Aragon', 'female', { birthDate: '1485', deathDate: '1536', birthPlace: 'Alcalá de Henares', deathPlace: 'Kimbolton', notes: 'First wife of Henry VIII; mother of Mary I. Marriage annulled in 1533.' });
    b.marry(arthur, catherineA);

    // Henry VIII's six wives, in order.
    const uH8_cath = b.marry(henry8, catherineA);
    const anneB = b.person('anne_b', 'Anne', 'Boleyn', 'female', { birthDate: '~1501', deathDate: '1536', birthPlace: 'Blickling', deathPlace: 'Tower of London', notes: 'Second wife of Henry VIII; mother of Elizabeth I. Executed in 1536.' });
    const uH8_anne = b.marry(henry8, anneB);
    const janeS = b.person('jane_s', 'Jane', 'Seymour', 'female', { birthDate: '~1508', deathDate: '1537', birthPlace: 'Wolfhall', deathPlace: 'Hampton Court', notes: 'Third wife; mother of Edward VI. Died soon after childbirth.' });
    const uH8_jane = b.marry(henry8, janeS);
    const anneC = b.person('anne_c', 'Anne', 'of Cleves', 'female', { birthDate: '1515', deathDate: '1557', birthPlace: 'Düsseldorf', deathPlace: 'Chelsea, London', notes: 'Fourth wife; marriage annulled after six months.' });
    b.marry(henry8, anneC);
    const catherineH = b.person('catherine_h', 'Catherine', 'Howard', 'female', { birthDate: '~1523', deathDate: '1542', deathPlace: 'Tower of London', notes: 'Fifth wife; executed in 1542.' });
    b.marry(henry8, catherineH);
    const catherineP = b.person('catherine_p', 'Catherine', 'Parr', 'female', { birthDate: '1512', deathDate: '1548', deathPlace: 'Sudeley Castle', notes: 'Sixth wife; outlived Henry VIII.' });
    b.marry(henry8, catherineP);

    const mary1 = b.person('mary1', 'Mary I', 'Tudor', 'female', { birthDate: '1516', deathDate: '1558', birthPlace: 'Greenwich', deathPlace: "St James's Palace", notes: 'Queen of England; restored Catholicism, known as "Bloody Mary".' });
    b.kids(uH8_cath, mary1);
    const elizabeth1 = b.person('elizabeth1', 'Elizabeth I', 'Tudor', 'female', { birthDate: '1533', deathDate: '1603', birthPlace: 'Greenwich', deathPlace: 'Richmond, London', notes: 'The Virgin Queen; her reign was the Elizabethan golden age. The Tudor line ended with her.' });
    b.kids(uH8_anne, elizabeth1);
    const edward6 = b.person('edward6', 'Edward VI', 'Tudor', 'male', { birthDate: '1537', deathDate: '1553', birthPlace: 'Hampton Court', deathPlace: 'Greenwich', notes: 'Became king at nine; died at fifteen.' });
    b.kids(uH8_jane, edward6);

    const philip2 = b.person('philip2', 'Philip II', 'of Spain', 'male', { birthPlace: 'Valladolid', deathPlace: 'El Escorial', birthDate: '1527', deathDate: '1598' });
    b.marry(mary1, philip2);

    // Margaret Tudor -> Stuart line to Mary, Queen of Scots.
    const james4 = b.person('james4', 'James IV', 'of Scotland', 'male', { deathPlace: 'Branxton', birthDate: '1473', deathDate: '1513' });
    const uMargaret = b.marry(margaretT, james4);
    const james5 = b.person('james5', 'James V', 'of Scotland', 'male', { birthPlace: 'Linlithgow', deathPlace: 'Falkland', birthDate: '1512', deathDate: '1542' });
    b.kids(uMargaret, james5);
    const maryG = b.person('mary_g', 'Mary', 'of Guise', 'female', { birthPlace: 'Bar-le-Duc', deathPlace: 'Edinburgh', birthDate: '1515', deathDate: '1560' });
    const uJames5 = b.marry(james5, maryG);
    const maryQ = b.person('mary_q', 'Mary', 'Stuart', 'female', { birthDate: '1542', deathDate: '1587', birthPlace: 'Linlithgow', deathPlace: 'Fotheringhay', notes: 'Mary, Queen of Scots; executed on the orders of Elizabeth I.' });
    b.kids(uJames5, maryQ);

    // Mary Tudor -> Brandon -> Lady Jane Grey.
    const brandon = b.person('brandon', 'Charles', 'Brandon', 'male', { deathPlace: 'Guildford', birthDate: '~1484', deathDate: '1545' });
    const uMaryT = b.marry(maryT, brandon);
    const frances = b.person('frances', 'Frances', 'Brandon', 'female', { birthPlace: 'Hatfield', deathPlace: 'Richmond, London', birthDate: '1517', deathDate: '1559' });
    b.kids(uMaryT, frances);
    const henryG = b.person('henry_g', 'Henry', 'Grey', 'male', { deathPlace: 'Tower of London', birthDate: '1517', deathDate: '1554' });
    const uFrances = b.marry(frances, henryG);
    const janeG = b.person('jane_g', 'Jane', 'Grey', 'female', { birthDate: '~1537', deathDate: '1554', birthPlace: 'Bradgate Park', deathPlace: 'Tower of London', notes: 'The "Nine Days\' Queen"; deposed by Mary I and executed.' });
    b.kids(uFrances, janeG);

    return { data: b.build(TUDOR_PLACES), focus: henry8 };
}

const PREMYSLIDS = buildPremyslids();
const TUDORS = buildTudors();

export type DemoLang = 'cs' | 'en';

/** A fresh copy of the demo tree for the language (cs = Přemyslids, else Tudors). */
export function getDemoTree(lang: DemoLang): StromData {
    const source = lang === 'cs' ? PREMYSLIDS.data : TUDORS.data;
    return structuredClone(source);
}

/** Id of the person to focus after loading the demo (sv. Václav / Henry VIII). */
export function getDemoFocus(lang: DemoLang): PersonId {
    return lang === 'cs' ? PREMYSLIDS.focus : TUDORS.focus;
}
